---
- name: Download latest WordPress 
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes
- name: Check if WordPress already exists in root
  stat:
    path: /var/www/html/wp-config-sample.php
  register: wp_installed
- name: Move WordPress files to root of web directory
  ansible.builtin.shell: mv /var/www/html/wordpress/* /var/www/html/
  when: not wp_installed.stat.exists
- name: Remove leftover WordPress folder
  file:
    path: /var/www/html/wordpress
    state: absent
- name: Set correct ownership
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes
- name: Set correct permissions
  file:
    path: /var/www/html
    mode: '0755'
    recurse: yes
- name: Copy sample config
  copy:
    src: /var/www/html/wp-config-sample.php
    dest: /var/www/html/wp-config.php
    remote_src: yes
- name: Setup wp-config.php database settings
  replace: 
    path: /var/www/html/wp-config.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: "database_name_here", replace: "wordpress_db" }
    - { regexp: "username_here", replace: "wp_user" }
    - { regexp: "password_here", replace: "StrongPassword123!" }
