---

- name: Update apt package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600 #Cache validity in seconds (optional)

- name: Upgrade all packages to the latest version
  apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes


